const users = [
  {
    id: 1,
    first_name: "Mark Jason",
    last_name: "Delima",
    email:"markjason.delima@email.com",
    category: "Basic Category",
    total_items: "20",
    score: "19",
    taken_category: 1,
  },
  {
    id: 2,
    first_name: "John",
    last_name: "Doe",
    email:"john.doe@email.com",
    category: "Basic Category Testing",
    total_items: "20",
    score: "14",
    taken_category: 3,
  },
  {
    id: 3,
    first_name: "Daniel",
    last_name: "Shors Escabaca",
    email:"daniel.shorsesbaca@email.com",
    category: "Basic Testing Category 4",
    total_items: "20",
    score: "11",
    taken_category: 4,
  },
  {
    id: 4,
    first_name: "Jasper",
    last_name: "Shors",
    email: "testing123@email.com",
    category: "Basic Testing Category 4",
    total_items: "20",
    score: "11",
    taken_category: 4,
  },
  {
    id: 5,
    first_name: "Cardo",
    last_name: "Dalisay",
    email: "cardo.dalisay@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 4,
  },

  {
    id: 6,
    first_name: "Lee",
    last_name: "Luh",
    email: "Luh@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 7,
    first_name: "Nagkakuyaw",
    last_name: "Man",
    email: "Kuyawan@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 8,
    first_name: "Ra",
    last_name: "Testing",
    email: "Ambot@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 9,
    first_name: "Testing",
    last_name: "Ra",
    email: "John.Russel@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 10,
    first_name: "secret",
    last_name: "ambot",
    email: "testing@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 11,
    first_name: "John",
    last_name: "Fontillas",
    email: "John@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },

  {
    id: 12,
    first_name: "Russel",
    last_name: "Fontillas",
    email: "Russel@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },
  {
    id: 13,
    first_name: "Russel",
    last_name: "Fontillas",
    email: "Russel@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },
  {
    id: 14,
    first_name: "Russel",
    last_name: "Fontillas",
    email: "Russel@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },
  {
    id: 15,
    first_name: "Russel",
    last_name: "Fontillas",
    email: "Russel@email.com",
    category: "Basic Training Testing",
    total_items: "50",
    score: "12",
    taken_category: 5,
  },
];

export default users;
